language: python
python:
 - "2.6"
 - "2.7"
 - "3.4"
install: python setup.py develop
script: ./runtests.sh
#notifications:
#    irc:
#        - "irc.freenode.net#threebean"
#    on_success: never
#    on_failure: always
